export const GOOGLE_AUTH_ASYNC = "GOOGLE_AUTH_ASYNC";
export const SEARCH_MSG = "SEARCH_MSG";
export const CARD_SEARCH_RESULTS_ASYNC = "CARD_SEARCH_RESULTS_ASYNC";
export const JOB_SEARCH_RESULTS_ASYNC = "JOB_SEARCH_RESULTS_ASYNC"
export const USER_CARD_ASYNC = "USER_CARD_ASYNC"
