export const GOOGLE_AUTH_ASYNC = "GOOGLE_AUTH_ASYNC";
export const CLEAR_USER_STATE = "CLEAR_USER_STATE";
export const SEARCH_MSG = "SEARCH_MSG";
export const CARD_SEARCH_RESULTS_ASYNC = "CARD_SEARCH_RESULTS_ASYNC";
